import {
  neon,
  type NeonQueryFunction,
  type NeonQueryPromise,
} from "@neondatabase/serverless";
import { buildDefaultCatalogData } from "./catalog-seed";

export type Db = NeonQueryFunction<false, false>;

let cached: Db | null = null;

/**
 * Returns the Neon Postgres query function. Requires DATABASE_URL in the
 * environment; the same connection string is injected into Vercel by the
 * Neon → Vercel integration.
 */
export function getDb(): Db {
  const url = process.env.DATABASE_URL;
  if (!url) {
    throw new Error(
      "DATABASE_URL is not set. Provide your Neon Postgres connection string in the environment.",
    );
  }
  cached ??= neon(url);
  return cached;
}

const DDL_STATEMENTS: string[] = [
  `create table if not exists categories (
    id integer generated by default as identity primary key,
    name text not null,
    sort_order integer not null default 0,
    constraint categories_name_key unique (name)
  )`,
  `create table if not exists attributes (
    id integer generated by default as identity primary key,
    type text not null check (type in ('series', 'glass', 'color', 'lock')),
    name text not null,
    sort_order integer not null default 0,
    constraint attributes_type_name_key unique (type, name)
  )`,
  `create table if not exists products (
    id integer generated by default as identity primary key,
    name text not null,
    category_id integer not null references categories (id),
    base_price numeric(12, 2) not null default 0,
    description text not null default '',
    default_series_id integer references attributes (id),
    default_glass_id integer references attributes (id),
    image_key text,
    image_path text,
    updated_at timestamptz not null default now(),
    constraint products_category_name_key unique (category_id, name)
  )`,
  `create table if not exists settings (
    id integer primary key,
    company_name text not null,
    logo_key text,
    address text not null default '',
    contact_numbers text not null default '',
    email text not null default '',
    tin text not null default '',
    bank_account_name text not null default '',
    bank_account_number text not null default '',
    bank_name text not null default '',
    bank_branch text not null default '',
    terms_conditions text not null default '',
    pdf_header text not null default '',
    updated_at timestamptz not null default now()
  )`,
  `create table if not exists quotations (
    id integer generated by default as identity primary key,
    quotation_number text not null,
    customer_name text not null,
    project_name text not null,
    project_address text not null default '',
    subtotal numeric(12, 2) not null default 0,
    discount numeric(12, 2) not null default 0,
    grand_total numeric(12, 2) not null default 0,
    total_sqft numeric(12, 2) not null default 0,
    item jsonb not null,
    status text not null default 'draft',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint quotations_number_key unique (quotation_number)
  )`,
  `create table if not exists glass_designs (
    id text primary key,
    name text not null default '',
    code text not null default '',
    description text not null default '',
    width_mm integer not null,
    height_mm integer not null,
    section text not null default 'Windows',
    type text not null default '',
    series text not null default '',
    unit text not null default 'm',
    spec jsonb not null default '{}'::jsonb,
    shapes jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  )`,
];

export type SchemaStatus = { seeded: boolean };

let schemaReady: Promise<SchemaStatus> | null = null;

/**
 * Makes sure the catalog schema exists, creating and seeding it on first use.
 * The result is memoized per process (at most a couple of round-trips per
 * cold start); failures are not cached so the next request retries.
 */
export function readySchema(): Promise<SchemaStatus> {
  schemaReady ??= ensureCatalogSchema().catch((error) => {
    schemaReady = null;
    throw error;
  });
  return schemaReady;
}

export async function ensureCatalogSchema(): Promise<SchemaStatus> {
  const db = getDb();
  for (const statement of DDL_STATEMENTS) {
    await db.query(statement);
  }
  const rows = await db.query(
    "select (select count(*) from products)::int as products, (select count(*) from settings)::int as settings",
  );
  const counts = rows[0] as { products: number; settings: number };
  if (counts.products > 0 || counts.settings > 0) {
    return { seeded: false };
  }
  await seedDefaults(db);
  return { seeded: true };
}

/**
 * Seeds the default catalog inside a single non-interactive transaction so a
 * concurrent first request can never observe a half-seeded database.
 */
async function seedDefaults(db: Db): Promise<void> {
  const data = buildDefaultCatalogData(new Date().toISOString());
  const { settings } = data;

  const queries: NeonQueryPromise<false, false>[] = [
    db.query(
      `insert into settings (
        id, company_name, address, contact_numbers, email, tin,
        bank_account_name, bank_account_number, bank_name, bank_branch,
        terms_conditions, pdf_header
      ) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
      on conflict (id) do nothing`,
      [
        settings.id,
        settings.companyName,
        settings.address,
        settings.contactNumbers,
        settings.email,
        settings.tin,
        settings.bankAccountName,
        settings.bankAccountNumber,
        settings.bankName,
        settings.bankBranch,
        settings.termsConditions,
        settings.pdfHeader,
      ],
    ),
  ];

  for (const category of data.categories) {
    queries.push(
      db.query(
        "insert into categories (id, name, sort_order) values ($1, $2, $3) on conflict (id) do nothing",
        [category.id, category.name, category.sortOrder],
      ),
    );
  }

  for (const attribute of data.attributes) {
    queries.push(
      db.query(
        "insert into attributes (id, type, name, sort_order) values ($1, $2, $3, $4) on conflict (id) do nothing",
        [attribute.id, attribute.type, attribute.name, attribute.sortOrder],
      ),
    );
  }

  for (const product of data.products) {
    queries.push(
      db.query(
        `insert into products (
          id, name, category_id, base_price, description,
          default_series_id, default_glass_id, image_path, updated_at
        ) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
        on conflict (id) do nothing`,
        [
          product.id,
          product.name,
          product.categoryId,
          product.basePrice,
          product.description,
          product.defaultSeriesId,
          product.defaultGlassId,
          product.imagePath,
          product.updatedAt,
        ],
      ),
    );
  }

  // Keep the identity sequences aligned with the explicitly seeded ids.
  for (const table of ["categories", "attributes", "products", "quotations"]) {
    queries.push(
      db.query(
        `select setval(
          pg_get_serial_sequence('${table}', 'id'),
          coalesce((select max(id) from ${table}), 1),
          (select count(*) from ${table}) > 0
        )`,
      ),
    );
  }

  await db.transaction(queries);
}
