import type { FinishedProject } from "./catalog-types";

export const defaultProjectsSeed: FinishedProject[] = [
  {
    id: 1,
    projectName: "Tara Louver & Jalousie Window Project",
    clientName: "Ms. Tara / Tara Residence",
    projectAddress: "Puerto Princesa City, Palawan",
    invoiceNumber: "INV-2026-TL01",
    invoiceDate: "September 18, 2026",
    totalAmount: 48500,
    fileName: "TaraLouverWindow.pdf",
    fileType: "application/pdf",
    fileSize: 184520,
    status: "completed",
    notes: "Owner finished invoice with custom louver and awning window drawings.",
    items: [
      {
        id: "tl-item-1",
        name: "4-inch Aluminum Jalousie Louver Window",
        category: "Windows",
        widthFt: 4,
        heightFt: 5,
        quantity: 6,
        rate: 950,
        total: 28500,
        series: "4-inch",
        glass: "6mm Annealed",
        color: "Dark Bronze",
        lock: "Standard Crescent",
        description: "4-inch adjustable louver ventilation window with Dark Bronze aluminum frame and 6mm annealed glass blades.",
        imageDataUrl: "/product-images/jalousie-window.svg",
      },
      {
        id: "tl-item-2",
        name: "38 Series Awning Transom Window",
        category: "Windows",
        widthFt: 4,
        heightFt: 2,
        quantity: 4,
        rate: 1100,
        total: 20000,
        series: "Series 38",
        glass: "6mm Annealed",
        color: "Dark Bronze",
        lock: "Standard Crescent",
        description: "Top-hinged awning transom window above louver frames.",
        imageDataUrl: "/product-images/awning-window.svg",
      },
    ],
    createdAt: "2026-09-18T10:00:00.000Z",
    updatedAt: "2026-09-18T10:00:00.000Z",
  },
  {
    id: 2,
    projectName: "Abin Residential Window & Sliding Door Package",
    clientName: "Engr. Abin",
    projectAddress: "San Vicente, Palawan",
    invoiceNumber: "INV-2026-AB02",
    invoiceDate: "September 12, 2026",
    totalAmount: 112600,
    fileName: "Abinnew.pdf",
    fileType: "application/pdf",
    fileSize: 245100,
    status: "completed",
    notes: "Completed invoice including 4-panel sliding window, 2-panel sliding window, and heavy duty sliding door.",
    items: [
      {
        id: "ab-item-1",
        name: "798 Series 4-Panel Sliding Window",
        category: "Windows",
        widthFt: 8,
        heightFt: 5,
        quantity: 2,
        rate: 1850,
        total: 74000,
        series: "Series 798",
        glass: "6mm Annealed",
        color: "Dark Bronze",
        lock: "Standard Crescent",
        description: "4-panel heavy duty sliding window with 1 x 3 tubular frame, Dark Bronze finish, 6mm annealed glass.",
        imageDataUrl: "/four-panel-window.png",
      },
      {
        id: "ab-item-2",
        name: "798 Series 2-Panel Sliding Window",
        category: "Windows",
        widthFt: 5,
        heightFt: 4,
        quantity: 3,
        rate: 1250,
        total: 22500,
        series: "Series 798",
        glass: "6mm Annealed",
        color: "Dark Bronze",
        lock: "Standard Crescent",
        description: "2-panel sliding window with operable left and right sashes.",
        imageDataUrl: "/product-images/2-panel-sliding-window.svg",
      },
      {
        id: "ab-item-3",
        name: "900 Series Heavy Duty Sliding Patio Door",
        category: "Doors",
        widthFt: 6,
        heightFt: 7,
        quantity: 1,
        rate: 2400,
        total: 16100,
        series: "Series 900",
        glass: "6mm Annealed",
        color: "Dark Bronze",
        lock: "Heavy Duty",
        description: "Aluminum framed sliding patio door with bottom track and flush handles.",
        imageDataUrl: "/product-images/sliding-door.svg",
      },
    ],
    createdAt: "2026-09-12T14:30:00.000Z",
    updatedAt: "2026-09-12T14:30:00.000Z",
  },
  {
    id: 3,
    projectName: "Joriz Commercial & Residential Glazing",
    clientName: "Joriz Development Corp.",
    projectAddress: "Roxas, Palawan",
    invoiceNumber: "INV-2026-JZ03",
    invoiceDate: "August 28, 2026",
    totalAmount: 86400,
    fileName: "Joriz.pdf",
    fileType: "application/pdf",
    fileSize: 198750,
    status: "completed",
    notes: "Custom awning windows and fixed storefront glass.",
    items: [
      {
        id: "jz-item-1",
        name: "38 Series 3-Panel Awning Window",
        category: "Windows",
        widthFt: 5,
        heightFt: 6,
        quantity: 2,
        rate: 1100,
        total: 33000,
        series: "Series 38",
        glass: "6mm Annealed",
        color: "White",
        lock: "Standard Crescent",
        description: "3-tier awning window configuration with powder coated white finish.",
        imageDataUrl: "/product-images/awning-window.svg",
      },
      {
        id: "jz-item-2",
        name: "Fixed Glass Showcase Window",
        category: "Windows",
        widthFt: 6,
        heightFt: 5,
        quantity: 2,
        rate: 900,
        total: 27000,
        series: "Middle-end",
        glass: "6mm Annealed",
        color: "White",
        lock: "Standard Crescent",
        description: "Fixed aluminum display glass window.",
        imageDataUrl: "/product-images/fixed-window.svg",
      },
      {
        id: "jz-item-3",
        name: "50 Series Casement / Swing Entrance Door",
        category: "Doors",
        widthFt: 3,
        heightFt: 7,
        quantity: 2,
        rate: 2800,
        total: 26400,
        series: "Series 50",
        glass: "6mm Annealed",
        color: "White",
        lock: "Heavy Duty",
        description: "Hinged aluminum swing door with lever lock.",
        imageDataUrl: "/product-images/casement-swing-door.svg",
      },
    ],
    createdAt: "2026-08-28T09:15:00.000Z",
    updatedAt: "2026-08-28T09:15:00.000Z",
  },
  {
    id: 4,
    projectName: "Pajara Storefront & Entrance Doors",
    clientName: "Pajara Commercial Plaza / Mr. Pajara",
    projectAddress: "National Highway, Palawan",
    invoiceNumber: "INV-2026-PJ04",
    invoiceDate: "September 05, 2026",
    totalAmount: 93500,
    fileName: "Pajara.pdf",
    fileType: "application/pdf",
    fileSize: 215400,
    status: "completed",
    notes: "Heavy duty double leaf ED door and counter windows.",
    items: [
      {
        id: "pj-item-1",
        name: "Double Leaf ED Commercial Entrance Door",
        category: "Doors",
        widthFt: 5.4,
        heightFt: 6.9,
        quantity: 2,
        rate: 18500,
        total: 37000,
        series: "Frameless",
        glass: "10mm Annealed",
        color: "Analok",
        lock: "Heavy Duty",
        description: "10mm annealed glass double entrance door with stainless steel push/pull bars and patch fittings.",
        imageDataUrl: "/product-images/double-leaf-ed-door.svg",
      },
      {
        id: "pj-item-2",
        name: "Fixed-Sliding Service Counter Window",
        category: "Windows",
        widthFt: 5,
        heightFt: 4,
        quantity: 3,
        rate: 1950,
        total: 39000,
        series: "Series 798",
        glass: "6mm Annealed",
        color: "Analok",
        lock: "Standard Crescent",
        description: "Combination fixed top transom and bottom sliding counter pass-through window.",
        imageDataUrl: "/product-images/fixed-sliding-counter-window.svg",
      },
      {
        id: "pj-item-3",
        name: "Single Leaf ED Door with Push Bar",
        category: "Doors",
        widthFt: 3,
        heightFt: 7,
        quantity: 1,
        rate: 9800,
        total: 17500,
        series: "Frameless",
        glass: "10mm Annealed",
        color: "Analok",
        lock: "Heavy Duty",
        description: "10mm clear tempered/annealed glass entrance door with stainless steel handle.",
        imageDataUrl: "/product-images/single-leaf-ed-door.svg",
      },
    ],
    createdAt: "2026-09-05T11:45:00.000Z",
    updatedAt: "2026-09-05T11:45:00.000Z",
  },
  {
    id: 5,
    projectName: "Ranchero Glass Enclosure & Bi-Fold Doors",
    clientName: "Ranchero Farm & Resort",
    projectAddress: "Napsan, Palawan",
    invoiceNumber: "INV-2026-RN05",
    invoiceDate: "August 15, 2026",
    totalAmount: 138200,
    fileName: "Ranchero.pdf",
    fileType: "application/pdf",
    fileSize: 310200,
    status: "completed",
    notes: "Multi-panel folding doors and insect screened sliding windows.",
    items: [
      {
        id: "rn-item-1",
        name: "900 Series Bi-Fold 4-Leaf Folding Door",
        category: "Doors",
        widthFt: 8,
        heightFt: 7,
        quantity: 1,
        rate: 3200,
        total: 89600,
        series: "Series 900",
        glass: "6mm Annealed",
        color: "Dark Bronze",
        lock: "Heavy Duty",
        description: "4-leaf bi-fold folding aluminum and glass door system with heavy duty hardware.",
        imageDataUrl: "/product-images/bi-fold-door.svg",
      },
      {
        id: "rn-item-2",
        name: "798 Series 3-Panel Sliding Window with Net",
        category: "Windows",
        widthFt: 6,
        heightFt: 4,
        quantity: 3,
        rate: 1750,
        total: 36000,
        series: "Series 798",
        glass: "6mm Annealed",
        color: "Dark Bronze",
        lock: "Standard Crescent",
        description: "3-panel sliding window with insect screen mesh.",
        imageDataUrl: "/product-images/3-panel-sliding-net.svg",
      },
      {
        id: "rn-item-3",
        name: "Folding Window Balcony Enclosure",
        category: "Windows",
        widthFt: 6,
        heightFt: 4,
        quantity: 1,
        rate: 2200,
        total: 12600,
        series: "Series 900",
        glass: "6mm Annealed",
        color: "Dark Bronze",
        lock: "Standard Crescent",
        description: "Multi-panel folding window system for resort balcony.",
        imageDataUrl: "/product-images/folding-window.svg",
      },
    ],
    createdAt: "2026-08-15T16:20:00.000Z",
    updatedAt: "2026-08-15T16:20:00.000Z",
  },
];
